# Generated by Django 2.2.4 on 2019-09-08 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_q', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_signature', models.TextField(default='')),
                ('method_description', models.TextField(default='')),
                ('interview_question_api', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_q.InterviewAPI')),
            ],
        ),
    ]
