# Generated by Django 2.1.4 on 2019-09-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method_signature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='method',
            name='name',
        ),
    ]
