# Generated by Django 2.2.4 on 2019-10-03 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('method_signature', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='methodsignature',
            name='method_description',
        ),
    ]
