# Generated by Django 2.2.4 on 2019-09-25 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190925_0058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteuser',
            old_name='company',
            new_name='company_org',
        ),
        migrations.AddField(
            model_name='siteuser',
            name='user_role',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
