# Generated by Django 2.2.4 on 2019-09-27 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190925_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('expiration_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('FREE', 'Free Plan'), ('MONTHLY_CREATOR', 'Monthly Pro ($30/Mo)')], default='FREE', max_length=25)),
                ('initiated_on', models.DateTimeField(blank=True, null=True)),
                ('terminated_on', models.DateTimeField(blank=True, null=True)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SubscriptionCouponCode')),
            ],
        ),
        migrations.AddField(
            model_name='siteuser',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.Subscription'),
        ),
    ]
