# Generated by Django 2.2.4 on 2019-10-02 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_subscriptioncouponcode_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptioncouponcode',
            name='curr_redeems',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscriptioncouponcode',
            name='max_redeems',
            field=models.IntegerField(default=1),
        ),
    ]
