# Generated by Django 2.2.4 on 2019-10-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20191002_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan_type',
            field=models.CharField(choices=[('SHY', 'Free Plan'), ('ASKER', 'Basic Plan'), ('INQUISITOR', 'Pro Plan'), ('INTERROGATOR', 'Premium Plan')], default='SHY', max_length=35),
        ),
    ]
