# Generated by Django 2.2.4 on 2019-10-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20191017_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='num_questions_made',
            field=models.IntegerField(default=0),
        ),
    ]
