# Generated by Django 2.2.4 on 2019-12-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_siteuser_num_questions_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='payment_method',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
