# Generated by Django 2.2.4 on 2019-12-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_siteuser_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='customer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='payment_method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
