# Generated by Django 2.2.4 on 2019-12-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191216_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
