# Generated by Django 2.2.4 on 2019-12-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_siteuser_stripe_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='auto_renew',
            field=models.BooleanField(default=False),
        ),
    ]
