# Generated by Django 2.2.4 on 2019-09-10 11:15

from django.db import migrations, models
import django.db.models.deletion
import solution_code.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interview_q', '0003_auto_20190910_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_file', models.FileField(null=True, upload_to=solution_code.models.SolutionCode.upload_path_handler)),
                ('interview_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='interview_q.InterviewQuestion')),
            ],
        ),
    ]
