# Generated by Django 2.2.4 on 2019-09-09 21:38

from django.db import migrations, models
import example_code.models


class Migration(migrations.Migration):

    dependencies = [
        ('example_code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examplecode',
            name='code_file',
            field=models.FileField(null=True, upload_to=example_code.models.ExampleCode.upload_path_handler),
        ),
        migrations.AlterField(
            model_name='examplecode',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
