# Generated by Django 2.1.4 on 2019-09-02 22:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='creation_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='has_completed',
            field=models.BooleanField(default=False),
        ),
    ]
