# Generated by Django 2.2.4 on 2019-09-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='expire_time',
            field=models.DateTimeField(null=True),
        ),
    ]
