# Generated by Django 2.2.4 on 2019-09-25 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0002_interviewquestioninstance_expire_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='how_many_minutes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='is_minutes_expiration',
            field=models.BooleanField(default=False),
        ),
    ]
