# Generated by Django 2.2.4 on 2019-09-26 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0003_auto_20190925_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='timezone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
