# Generated by Django 2.2.4 on 2019-09-26 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0004_interviewquestioninstance_timezone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestioninstance',
            name='timezone',
        ),
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='start_time_date_str',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
