# Generated by Django 2.2.4 on 2019-09-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0005_auto_20190926_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='can_preview',
            field=models.BooleanField(default=False),
        ),
    ]
