# Generated by Django 2.2.4 on 2019-10-17 19:03

from django.db import migrations, models
import interview_q_instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0008_interviewquestioninstance_current_working_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='live_interview_id',
            field=models.CharField(default=interview_q_instance.models.make_uuid, editable=False, max_length=36),
        ),
    ]
