# Generated by Django 2.2.4 on 2019-10-21 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0009_interviewquestioninstance_live_interview_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='creator_email',
            field=models.CharField(default='maker@maker.com', max_length=128),
            preserve_default=False,
        ),
    ]
