# Generated by Django 2.2.4 on 2019-10-24 16:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('interview_q_instance', '0010_interviewquestioninstance_creator_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='interviewee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
