# Generated by Django 2.2.4 on 2019-11-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0012_auto_20191111_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='new_files_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
