# Generated by Django 2.2.4 on 2019-11-19 17:24

from django.db import migrations, models
import interview_q_instance.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0013_interviewquestioninstance_new_files_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestioninstance',
            name='id',
            field=models.BigIntegerField(default=interview_q_instance.models.make_pk, primary_key=True, serialize=False),
        ),
    ]
