# Generated by Django 2.2.4 on 2019-12-12 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0014_auto_20191119_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestioninstance',
            name='interviewee',
        ),
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='is_anon_user',
            field=models.BooleanField(default=False),
        ),
    ]
