# Generated by Django 2.2.4 on 2019-12-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q_instance', '0015_auto_20191212_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestioninstance',
            name='ip_addr',
            field=models.CharField(default='', max_length=128),
        ),
    ]
