# Generated by Django 2.2.4 on 2019-09-10 00:24

from django.db import migrations, models
import interview_code_file.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_code_file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcodefile',
            name='code_file',
            field=models.FileField(null=True, upload_to=interview_code_file.models.InterviewCodeFile.upload_path_handler),
        ),
        migrations.AddField(
            model_name='interviewcodefile',
            name='name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
