# Generated by Django 2.2.4 on 2019-09-11 18:27

from django.db import migrations, models
import interview_code_file.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_code_file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportcode',
            name='code_file',
            field=models.FileField(default='', upload_to=interview_code_file.models.SupportCode.upload_path_handler),
            preserve_default=False,
        ),
    ]
