# Generated by Django 2.2.4 on 2019-09-07 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='language',
            field=models.CharField(default='Python3', max_length=128),
        ),
        migrations.AddField(
            model_name='interviewquestion',
            name='solution',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
