# Generated by Django 2.1.4 on 2019-09-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='time_limit_minutes',
            field=models.IntegerField(default=60),
        ),
    ]
