# Generated by Django 2.2.4 on 2019-09-10 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0002_interviewquestion_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='solution',
        ),
        migrations.RemoveField(
            model_name='interviewquestion',
            name='starter_code',
        ),
    ]
