# Generated by Django 2.1.4 on 2019-09-02 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_q', '0001_initial'),
        ('interview_q', '0002_interviewquestion_time_limit_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='api',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_q.InterviewAPI'),
        ),
    ]
