# Generated by Django 2.1.4 on 2019-09-02 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0003_interviewquestion_api'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
