# Generated by Django 2.2.4 on 2019-10-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0004_remove_interviewquestion_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='network_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
