# Generated by Django 2.2.4 on 2019-10-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0006_interviewquestion_dependency_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='allow_stdout',
            field=models.BooleanField(default=False),
        ),
    ]
