# Generated by Django 2.2.4 on 2019-10-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0007_interviewquestion_allow_stdout'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='banned_imports',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
