# Generated by Django 2.2.4 on 2019-10-30 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0008_interviewquestion_banned_imports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewquestion',
            name='dependency_file',
        ),
    ]
