# Generated by Django 2.2.4 on 2019-10-30 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0009_remove_interviewquestion_dependency_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='dependencies',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
