# Generated by Django 2.2.4 on 2019-10-30 17:07

from django.db import migrations, models
import interview_q.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0010_interviewquestion_dependencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='dependency_file',
            field=models.FileField(null=True, upload_to=interview_q.models.InterviewQuestion.upload_path_handler),
        ),
    ]
