# Generated by Django 2.2.4 on 2019-11-11 16:59

from django.db import migrations, models
import interview_q.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0012_remove_interviewquestion_dependency_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='id',
            field=models.CharField(default=interview_q.models.make_uuid, max_length=36, primary_key=True, serialize=False),
        ),
    ]
