# Generated by Django 2.2.4 on 2019-11-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0015_auto_20191111_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='allow_new_files',
            field=models.BooleanField(default=False),
        ),
    ]
