# Generated by Django 2.2.4 on 2019-11-18 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0016_interviewquestion_allow_new_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='name',
            field=models.CharField(max_length=512),
        ),
    ]
