# Generated by Django 2.2.4 on 2019-11-19 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0019_auto_20191119_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewquestion',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
