# Generated by Django 2.2.4 on 2019-11-26 01:51

from django.db import migrations, models
import interview_q.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0021_interviewquestion_display_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewquestion',
            name='display_id',
            field=models.BigIntegerField(default=interview_q.models.make_pk, unique=True),
        ),
    ]
