# Generated by Django 2.2.4 on 2019-09-10 12:45

from django.db import migrations, models
import interview_test_case.models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_test_case', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewtestcase',
            name='body',
        ),
        migrations.AddField(
            model_name='interviewtestcase',
            name='code_file',
            field=models.FileField(null=True, upload_to=interview_test_case.models.InterviewTestCase.upload_path_handler),
        ),
    ]
