# Generated by Django 2.2.4 on 2019-09-16 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('interview_q', '0004_remove_interviewquestion_api'),
        ('api_q', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewapi',
            name='interview_question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='interview_q.InterviewQuestion'),
            preserve_default=False,
        ),
    ]
