# Generated by Django 2.1.4 on 2019-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_q', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewapi',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
